import { useEffect, useMemo, useState } from "react";

type RunSummary = {
  id: string;
  createdAt: string;
  state: string;
  issueId: string;
  projectName: string;
  finalVerdict: string | null;
  human: { status: string; reason?: string };
  rootDir: string;
};

type LoadedRun = {
  run: RunSummary & Record<string, unknown>;
  issue?: Record<string, unknown>;
  evidence?: Record<string, unknown>;
  diagnosis?: Record<string, unknown>;
  verification?: Record<string, unknown>;
  patch?: string;
  sourceCandidates?: unknown[];
};

/**
 * Dashboard reads run artifacts via Vite middleware-less static import path.
 * For local MVP, paste a run directory JSON index or load from /@fs when available.
 * We also support dropping a runs manifest generated by the CLI serve helper.
 */
export function App() {
  const [runs, setRuns] = useState<RunSummary[]>([]);
  const [selected, setSelected] = useState<string | null>(null);
  const [loaded, setLoaded] = useState<LoadedRun | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [manualRoot, setManualRoot] = useState("");

  useEffect(() => {
    // Try optional manifest at public/runs.json (generated or copied for demos)
    fetch("/runs.json")
      .then((r) => (r.ok ? r.json() : []))
      .then((data) => {
        if (Array.isArray(data)) setRuns(data as RunSummary[]);
      })
      .catch(() => undefined);
  }, []);

  const selectedRun = useMemo(
    () => runs.find((r) => r.id === selected) ?? null,
    [runs, selected],
  );

  async function loadFromPath(rootDir: string, id: string) {
    setError(null);
    try {
      // Browser cannot read arbitrary FS; for local demo we expect files under /artifacts-demo or public
      const base = `/runs/${id}`;
      const run = await fetchJson(`${base}/run.json`);
      const issue = await fetchJsonOptional(`${base}/issue.json`);
      const evidence = await fetchJsonOptional(`${base}/evidence.json`);
      const diagnosis = await fetchJsonOptional(`${base}/diagnosis.json`);
      const verification = await fetchJsonOptional(`${base}/verification.json`);
      const patch = await fetchTextOptional(`${base}/patch.diff`);
      const sourceCandidatesRaw = await fetchJsonOptional(
        `${base}/artifacts/source-candidates.json`,
      );
      const sourceCandidates = Array.isArray(sourceCandidatesRaw)
        ? (sourceCandidatesRaw as unknown[])
        : undefined;
      setLoaded({
        run: run as LoadedRun["run"],
        issue,
        evidence,
        diagnosis,
        verification,
        patch: patch ?? undefined,
        sourceCandidates,
      });
      setSelected(id);
      void rootDir;
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    }
  }

  return (
    <>
      <header>
        <div>
          <strong>ReproSight</strong>{" "}
          <span className="muted">local run review</span>
        </div>
        <span className="badge">approval does not commit target repos</span>
      </header>
      <main>
        <section className="list">
          <div className="card" style={{ margin: 12 }}>
            <div className="muted" style={{ marginBottom: 8 }}>
              Load demo/public runs from <code>/runs/&lt;id&gt;/</code> or paste a
              run id served by the static host.
            </div>
            <input
              style={{ width: "100%", marginBottom: 8 }}
              placeholder="run id"
              value={manualRoot}
              onChange={(e) => setManualRoot(e.target.value)}
            />
            <button
              type="button"
              onClick={() => loadFromPath("", manualRoot)}
              style={{ width: "100%" }}
            >
              Load run
            </button>
          </div>
          {runs.map((r) => (
            <button
              key={r.id}
              type="button"
              className={selected === r.id ? "active" : ""}
              onClick={() => loadFromPath(r.rootDir, r.id)}
            >
              <div>{r.issueId}</div>
              <div className="muted">
                {r.state} · {r.finalVerdict ?? "—"}
              </div>
            </button>
          ))}
          {!runs.length && (
            <div className="muted" style={{ padding: 14 }}>
              No /runs.json manifest. CLI reports remain usable without the
              dashboard.
            </div>
          )}
        </section>
        <section className="detail">
          {error && <div className="card">{error}</div>}
          {!loaded && !error && (
            <div className="card muted">
              Select a run to inspect before/after evidence, source candidates,
              patch, and regression matrix.
            </div>
          )}
          {loaded && (
            <>
              <div className="card">
                <h2 style={{ marginTop: 0 }}>
                  {String(loaded.issue?.title ?? loaded.run.issueId)}
                </h2>
                <div className="muted">
                  {loaded.run.id} · {loaded.run.state} · human{" "}
                  {loaded.run.human?.status}
                </div>
              </div>
              <div className="grid">
                <div className="card">
                  <strong>Before</strong>
                  <div>
                    <img src={`/runs/${loaded.run.id}/artifacts/before.png`} alt="before" />
                  </div>
                </div>
                <div className="card">
                  <strong>After</strong>
                  <div>
                    <img src={`/runs/${loaded.run.id}/artifacts/after.png`} alt="after" />
                  </div>
                </div>
              </div>
              <div className="card">
                <strong>Source candidates</strong>
                <pre>
                  {JSON.stringify(
                    loaded.sourceCandidates ??
                      (loaded.evidence as { sourceCandidates?: unknown })
                        ?.sourceCandidates ??
                      [],
                    null,
                    2,
                  )}
                </pre>
              </div>
              <div className="card">
                <strong>Patch</strong>
                <pre>{loaded.patch ?? "(no patch)"}</pre>
              </div>
              <div className="card">
                <strong>Verification / regressions</strong>
                <pre>{JSON.stringify(loaded.verification ?? {}, null, 2)}</pre>
              </div>
              {selectedRun && (
                <div className="card muted">
                  Manifest entry project: {selectedRun.projectName}
                </div>
              )}
            </>
          )}
        </section>
      </main>
    </>
  );
}

async function fetchJson(url: string): Promise<unknown> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to load ${url}: ${res.status}`);
  return res.json();
}

async function fetchJsonOptional(url: string): Promise<Record<string, unknown> | undefined> {
  const res = await fetch(url);
  if (!res.ok) return undefined;
  return (await res.json()) as Record<string, unknown>;
}

async function fetchTextOptional(url: string): Promise<string | null> {
  const res = await fetch(url);
  if (!res.ok) return null;
  return res.text();
}
